### ISSUE TITLE
Numbered List Not Working

### ISSUE THREAD

**Issue by Jessie-Devine** [Montana-Media-Arts/341-work#15]
Hello! So, my numbered list in Brackets looks perfect (even in the Live Preview), but now that it's been pushed to GitHub.com it doesn't render properly. It just looks like a paragraph. Any ideas?

**Comment by marchendrickson** [comment]
Try adding in another blank line in after the end of your last paragraph and the beginning of the numbered list.

**Comment by Jessie-Devine** [comment]
@marchendrickson Ah! Thanks! That worked perfectly.
