### ISSUE TITLE
Help With Powershell

### ISSUE THREAD

**Issue by gordonty** [Montana-Media-Arts/341-work#7]
Does anyone know how to use powershell for windows or know a really good place to learn? I'm struggling and am just frustrated with it. I can't seem to do anything that we are asked to do for this class. I'd greatly appreciate any help.

**Comment by marchendrickson** [comment]
[https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/powershell-beginners-guide.md](url)

Have you tried using this? I followed through the section and it was helpful to start with but am looking for other resources as well to get more familiar with it.

**Comment by gordonty** [comment]
@marchendrickson I'm not sure that I have but when I clicked on it just now I receive a page not found message. I did however notice that when I downloaded GitHub it also downloaded GitShell which seems to be powershell specifically for github files. When I tried it out it seemed to work for the assignment. Thanks for suggesting that link.

**Comment by michaelmusick** [comment]
Git shell will do a lot of the same things. 

I am sorry @gordonty that powershell has been a problem. What about it has not been working correctly?

Is anyone else having this problem?

--
Michael Musick 

michaelmusick.com

**Comment by gordonty** [comment]
@michaelmusick I am just having some trouble learning how to use it so I spend more time frustrated then doing any of the actual assignment. I have had an easier time figuring out Git Shell which has allowed me to get the work done.

**Comment by KaylinKeya** [comment]
@gordonty I have been using GitBash for my windows computer and that worked great for me. It automatically downloaded along with the GitHub app. Hope this helps.

**Comment by OliviaColeman** [comment]
@michaelmusick I cannot figure out PowerShell. The instructor videos must have been made using a different operating system. None of the commands work and the instructions just don't seem to help. I cannot find any useful videos online to help me understand. It would be helpful if you created a help video with Microsoft PowerShell for the people that have a Windows computer. I still cannot figure out how to create a file in PowerShell and open it. I created a file in notepad and it will not open in Atom. I'm going to fail this class if I cannot figure this out.

**Comment by michaelmusick** [comment]
Hey @OliviaColeman, there is no way to account for all of the differences in various peoples computers and OS's. I have tested these steps on a PC and they have worked just fine. I understand your concern and will try to help. I am sorry there are not a ton of resources on the web, most development occurs on Unix-based systems (linux or macOS), hence all of the info for those systems. But the information is out there, keep working on your google search terms.

Now, with regard to your current issue. Which I think, from your short description is just getting around in PowerShell?

**In PowerShell:** and _NOT_ command prompt (cmd.exe).
To create a new directory in powershell you should be able to type:
`mkdir testDir` or `new-item -path ./testDir -itemtype directory`.
These have both been tested as working on Windows OS PowerShell. 

You can then change in to the directory using `cd testDir`.

To create a new file in PowerShell you should be able to simply use
`New-Item nameOfFile.md`

If you are on an older version of PowerShell/windows OS, the perhaps try the following more explicit command, as listed in the PowerShell tutorial linked from the class.
`new-item -type file -path testFile.md`

If that still doesn't work, you can use the `-Force` flag, which will overwrite any previous file if it exists, while guaranteeing creation. 

To open a file, if you have installed Atom, it should have automatically installed powershell commands for you. You can try;
`atom .` -> to open the entire directory in atom. 

If this does nothing, please check your atom install. Alternatively, you can type `explorer .` to open an explorer window in the current directory. You could then right-click the file and select "open with", then either notepad or atom. 




For more information on the `new-item` command in PowerShell, please look at Microsoft's manual page for the direction. https://msdn.microsoft.com/en-us/powershell/reference/4.0/microsoft.powershell.management/new-item

**Comment by laurasugi** [comment]
@OliviaColeman I am also on windows and was having a really difficult time with the tutorials.
Some things that helped were:
-Running powershell as administrator (Right click on the icon on the taskbar and the option should show up).
-Using Gitshell only for anything related to git.
-This one sounds silly, but after installing Atom for the first time my powershell didn't want to listen to me until I closed everything and restarted my laptop. After that it worked great!
Good luck and hope this helped a bit!
